# Generated by Django 5.1.7 on 2025-04-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_group_is_admin_alter_group_required_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
