# Generated by Django 5.1.7 on 2025-04-13 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_group_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='invite_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GroupMemberInvitedHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invited_chat_id', models.BigIntegerField()),
                ('group_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_history', to='bot.groupmember')),
            ],
        ),
    ]
