# Generated by Django 5.1.7 on 2025-04-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_groupmember_invite_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='required_channel_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
