# Generated by Django 5.1.7 on 2025-04-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_group_required_channel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmember',
            name='is_member',
        ),
    ]
