# Generated by Django 5.1.7 on 2025-04-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_channelmember_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmember',
            name='channel_chat',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='channelmember',
            name='user_chat',
            field=models.BigIntegerField(),
        ),
    ]
