# Generated by Django 5.1.7 on 2025-04-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_channelmember_channel_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='channelmember',
            unique_together={('channel_chat', 'user_chat')},
        ),
    ]
