# Generated by Django 5.1.7 on 2025-04-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_word_word_alter_channelmember_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='required_channel_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
