# Generated by Django 5.1.7 on 2025-07-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_group_required_channel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('message_id', models.BigIntegerField(unique=True)),
            ],
        ),
    ]
