# Generated by Django 5.1.7 on 2025-07-02 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_oldmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
