# Generated by Django 5.1.7 on 2025-07-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_oldmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldmessage',
            name='chat_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='oldmessage',
            name='message_id',
            field=models.BigIntegerField(),
        ),
    ]
